input.onButtonPressed(Button.A, function () {
    edubitTrafficLightBit.setLed(LedColor.Green, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.Off))
    edubitTrafficLightBit.setLed(LedColor.Red, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.On))
    basic.pause(2000)
    edubitTrafficLightBit.setLed(LedColor.Yellow, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.On))
    edubitTrafficLightBit.setLed(LedColor.Red, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.On))
    basic.pause(2000)
    edubitMotors.setServoPosition(ServoChannel.S1, 90)
    edubitRgbBit.showColor(0x00ff00)
    basic.pause(2000)
    edubitRgbBit.setPixelColor(0, 0xff0000)
    basic.pause(2000)
    edubitRgbBit.setPixelColor(1, 0xff0000)
    basic.pause(2000)
    edubitRgbBit.setPixelColor(2, 0xff0000)
    basic.pause(2000)
    edubitRgbBit.setPixelColor(3, 0xff0000)
    edubitMotors.setServoPosition(ServoChannel.S1, 0)
    basic.pause(2000)
    edubitTrafficLightBit.setLed(LedColor.Red, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.Off))
    edubitTrafficLightBit.setLed(LedColor.Green, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.On))
})
edubitTrafficLightBit.setLed(LedColor.Green, edubitTrafficLightBit.digitalStatePicker(DigitalIoState.On))
edubitMotors.setServoPosition(ServoChannel.S1, 90)
